function create_params(num_flowers)
	
	% CREATE_PARAMS initializes the global PARAM which houses the constants
	% used throught the program

	global PARAM
	
	PARAM.GRID_SCALE = 5;					% metres
	
	%Environment
	PARAM.NUM_FLOWERS = num_flowers;		% Total number of flowers distributed throughout the map
	PARAM.MIN_FLOWER_POLLEN = 114;			% mg    1000/1
	PARAM.MAX_FLOWER_POLLEN	= 114;			% mg
		
	%BEE
	PARAM.BEE_SPEED_NORMAL = 8.9408;		% m/s
	PARAM.BEE_SPEED_NORMAL_FULL = 5.36448;	% m/s
	PARAM.BEE_MAX_POLLEN_NORMAL	= 11;		% mg
	PARAM.BEE_SENSING_RADIUS = 3200;		% metres
	PARAM.BEE_MAX_DISTANCE_NORMAL = 1000;	% metres

	
% 	PARAM.BEE_SPEED_INFECTED = 4.5;			% m/s
% 	PARAM.BEE_SPEED_INFECTED_FULL = 2.6;	% m/s
	PARAM.BEE_MAX_POLLEN_INFECTED = PARAM.BEE_MAX_POLLEN_NORMAL * 0.8;		% mg
	PARAM.BEE_SENSING_RADIUS_INFECTED = 100;% metres
	PARAM.BEE_MAX_DISTANCE_INFECTED = 500;	% metres
	
	
	PARAM.BEE_SPEED_NORMAL = PARAM.BEE_SPEED_NORMAL / PARAM.GRID_SCALE * 60;
	PARAM.BEE_SPEED_NORMAL_FULL = PARAM.BEE_SPEED_NORMAL_FULL / PARAM.GRID_SCALE * 60;
	
	PARAM.BEE_SPEED_INFECTED = PARAM.BEE_SPEED_NORMAL;
	PARAM.BEE_SPEED_INFECTED_FULL = PARAM.BEE_SPEED_NORMAL_FULL;
	
	PARAM.BEE_SENSING_RADIUS = PARAM.BEE_SENSING_RADIUS / PARAM.GRID_SCALE;
	PARAM.BEE_SENSING_RADIUS_INFECTED = PARAM.BEE_SENSING_RADIUS_INFECTED / PARAM.GRID_SCALE;
	
	PARAM.BEE_MAX_DISTANCE_NORMAL = PARAM.BEE_MAX_DISTANCE_NORMAL / PARAM.GRID_SCALE;
	PARAM.BEE_MAX_DISTANCE_INFECTED = PARAM.BEE_MAX_DISTANCE_INFECTED / PARAM.GRID_SCALE;
    
    